/**
 * P7 — Assemble the .md per spec/21-app/17-file-formats.md §B with progressive
 * degradation when MD_FILE_MAX_BYTES is exceeded.
 */
import { MD_FILE_MAX_BYTES } from "@shared/constants";
import { ErrorCode, LogCategory } from "@shared/enums";
import { logger } from "@shared/logger";
import type { DomRect } from "@shared/types";
import { serializeDiff } from "./computed-diff";

export interface BuildMarkdownInput {
  url: string;
  title: string;
  capturedAtIso: string;
  viewportCssPx: { w: number; h: number };
  dpr: number;
  selectorPath: string;
  /** Optional XPath for the picked element. */
  xpath?: string;
  /** Optional suggested output filename (no path). Rendered in the Source block. */
  filename?: string;
  tag: string;
  id?: string;
  classes: string[];
  outerHtml: string;
  matchedCss: string;
  computedDiff: Record<string, string>;
  contextPngBase64: string;
  isolatedPngBase64?: string;
  extensionVersion: string;
  rect: DomRect;
}

export interface BuildMarkdownResult { md: string; truncated: string[] }

export function buildMarkdown(input: BuildMarkdownInput): BuildMarkdownResult {
  const truncated: string[] = [];

  const headerSelectors =
    `${input.tag}` +
    (input.id ? `#${input.id}` : "") +
    (input.classes.length ? `.${input.classes.slice(0, 3).join(".")}` : "");

  const compose = (opts: {
    includeIsolated: boolean;
    includeComputed: boolean;
    contextBase64: string;
    note?: string;
  }): string => {
    const parts: string[] = [];
    parts.push(`# Element export — ${headerSelectors}`);
    parts.push("");
    parts.push("## Source");
    parts.push(`- URL: ${input.url}`);
    parts.push(`- Captured: ${input.capturedAtIso}`);
    parts.push(`- Selector path: ${input.selectorPath}`);
    parts.push(`- CSS selector: ${input.selectorPath}`);
    if (input.xpath) parts.push(`- XPath: ${input.xpath}`);
    parts.push(`- Page title: ${input.title}`);
    parts.push(`- Viewport: ${input.viewportCssPx.w}×${input.viewportCssPx.h} CSS px @ DPR ${input.dpr}`);
    if (input.filename) parts.push(`- Suggested filename: ${input.filename}`);
    parts.push("");
    parts.push("## outerHTML");
    parts.push("```html");
    parts.push(input.outerHtml);
    parts.push("```");
    parts.push("");
    parts.push("## Matched CSS rules");
    parts.push("```css");
    parts.push(input.matchedCss || "/* no matched rules */");
    parts.push("```");
    if (opts.includeComputed) {
      parts.push("");
      parts.push("## Computed styles (diff vs default)");
      parts.push("```css");
      parts.push(serializeDiff(input.computedDiff) || "/* no diff */");
      parts.push("```");
    }
    parts.push("");
    parts.push("## Screenshot — in page context");
    parts.push(`![context](data:image/png;base64,${opts.contextBase64})`);
    if (opts.includeIsolated && input.isolatedPngBase64) {
      parts.push("");
      parts.push("## Screenshot — isolated");
      parts.push(`![isolated](data:image/png;base64,${input.isolatedPngBase64})`);
    }
    if (opts.note) {
      parts.push("");
      parts.push(`> ${opts.note}`);
    }
    parts.push("");
    parts.push("---");
    parts.push(`_Generated by Inspect Page v${input.extensionVersion}._`);
    parts.push("");
    return parts.join("\n");
  };

  // Try full version first.
  let md = compose({ includeIsolated: true, includeComputed: true, contextBase64: input.contextPngBase64 });
  if (utf8Bytes(md) <= MD_FILE_MAX_BYTES) return { md, truncated };

  // Degradation #1: drop isolated screenshot.
  truncated.push("isolated screenshot exceeded budget");
  md = compose({
    includeIsolated: false, includeComputed: true,
    contextBase64: input.contextPngBase64,
    note: "Truncated: isolated screenshot exceeded budget",
  });
  if (utf8Bytes(md) <= MD_FILE_MAX_BYTES) {
    logger.warn(LogCategory.Element, ErrorCode.W_MD_TRUNCATED, truncated.join("; "));
    return { md, truncated };
  }

  // Degradation #2: drop computed styles.
  truncated.push("computed styles exceeded budget");
  md = compose({
    includeIsolated: false, includeComputed: false,
    contextBase64: input.contextPngBase64,
    note: `Truncated: ${truncated.join("; ")}`,
  });
  logger.warn(LogCategory.Element, ErrorCode.W_MD_TRUNCATED, truncated.join("; "));
  // NOTE: spec also allows downscaling the context shot; left for v2 polish.
  return { md, truncated };
}

function utf8Bytes(s: string): number {
  return new TextEncoder().encode(s).length;
}

export async function blobToBase64(blob: Blob): Promise<string> {
  const buf = await blob.arrayBuffer();
  const bytes = new Uint8Array(buf);
  // Chunked btoa to avoid call-stack issues on large blobs.
  let binary = "";
  const chunk = 0x8000;
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode.apply(
      null,
      Array.from(bytes.subarray(i, i + chunk)),
    );
  }
  return btoa(binary);
}
