"""Emit Go inverted-field methods.

Per Rule 9 §4 the derived field MUST be a method (no `db` tag, no migration).
"""

from __future__ import annotations

HEADER = """// Code generated by linters-cicd/codegen/inverted_fields.py — DO NOT EDIT.
// Source: Rule 9, spec/04-database-conventions/01-naming-conventions.md
//
// Each method below is a computed inverse of a stored boolean column.
// The database stores ONLY the canonical (positive) form; the inverse
// is derived in code with a single negation. Never persist these.

package models
"""


def render(blocks) -> str:
    parts = [HEADER]
    for block in blocks:
        parts.append(_render_block(block))
    return "\n".join(parts) + "\n"


def _render_block(block) -> str:
    lines = [f"\n// --- {block.type_name}: derived inverses ---"]
    for f in block.fields:
        lines.append(
            f"\n// {f.inverse} is derived from {f.name} (db column: {f.db_column}).\n"
            f"func (m {block.type_name}) {f.inverse}() bool {{ return !m.{f.name} }}"
        )
    return "\n".join(lines)
