"""Emit PHP inverted-field traits.

Per Rule 9 each derived field is a method, not a property — no DB column,
no migration. We package them as a trait per source class so consumers
``use`` the trait inside the original class.
"""

from __future__ import annotations

HEADER = """<?php
/**
 * Code generated by linters-cicd/codegen/inverted_fields.py — DO NOT EDIT.
 * Source: Rule 9, spec/04-database-conventions/01-naming-conventions.md
 *
 * Each method below is a computed inverse of a stored boolean column.
 * The database stores ONLY the canonical (positive) form; the inverse
 * is derived in code with a single negation. Never persist these.
 */
"""


def render(blocks) -> str:
    parts = [HEADER]
    for block in blocks:
        parts.append(_render_trait(block))
    return "\n".join(parts) + "\n"


def _render_trait(block) -> str:
    name = f"{block.type_name}InvertedFields"
    lines = [f"\ntrait {name}\n{{"]
    for f in block.fields:
        lines.append(
            f"    /** Derived from \\${f.name} (db column: {f.db_column}). */\n"
            f"    public function get{f.inverse}(): bool\n"
            f"    {{\n"
            f"        return !$this->{f.name};\n"
            f"    }}\n"
        )
    lines.append("}")
    return "\n".join(lines)
