"""Emit TypeScript inverted-field mixins.

Per Rule 9 each derived field is a getter on a mixin class. Consumers
extend the mixin (or copy its body) into the original class via TS
declaration merging or a class-mixin helper.
"""

from __future__ import annotations

HEADER = """// Code generated by linters-cicd/codegen/inverted_fields.py — DO NOT EDIT.
// Source: Rule 9, spec/04-database-conventions/01-naming-conventions.md
//
// Each getter below is a computed inverse of a stored boolean column.
// The database stores ONLY the canonical (positive) form; the inverse
// is derived in code with a single negation. Never persist these.
"""


def render(blocks) -> str:
    parts = [HEADER]
    for block in blocks:
        parts.append(_render_block(block))
    return "\n".join(parts) + "\n"


def _render_block(block) -> str:
    name = f"{block.type_name}InvertedFields"
    field_decls = "\n".join(f"  readonly {f.name}!: boolean;" for f in block.fields)
    getters = "\n\n".join(_render_getter(f) for f in block.fields)
    return (
        f"\nexport abstract class {name} {{\n"
        f"{field_decls}\n\n"
        f"{getters}\n"
        f"}}"
    )


def _render_getter(f) -> str:
    return (
        f"  /** Derived from {f.name} (db column: {f.db_column}). */\n"
        f"  get {f.inverse}(): boolean {{\n"
        f"    return !this.{f.name};\n"
        f"  }}"
    )
