/**
 * Single source of truth for every visible string.
 * Source: spec/21-app/02-ui-panel.md §D.
 */
export const COPY = {
  appName: "Inspect Page",
  btnFullPage: "Export Full Page",
  btnPick: "Pick Element",
  btnCancel: "Cancel",
  btnCancelPicker: "Cancel picker",
  btnRetry: "Retry",
  btnCopyDetails: "Copy details",
  btnResetSettings: "Reset to defaults",
  btnOpenPanel: "Open panel on page",
  btnMinimize: "Minimize",
  btnClose: "Close",
  btnPopOut: "Open in new window",
  lblResizePanel: "Resize panel",
  btnThemeLight: "Switch to light theme",
  btnThemeDark: "Switch to dark theme",
  tabExport: "Export",
  tabPick: "Pick",
  tabInspect: "Inspect",
  inspectModeTitle: "Inspect Mode",
  inspectModePlaceholder: "Overview, Typography, Colors, Contrast and Inspector arrive in upcoming phases.",
  inspectOverviewTitle: "Overview",
  inspectLoading: "Collecting page snapshot…",
  inspectError: "Could not collect this page",
  inspectRetry: "Retry",
  inspectOpenDocs: "Open docs",
  inspectTypographyTitle: "Typography",
  inspectTypoHeadings: "Headings",
  inspectTypoBody: "Body",
  inspectTypoWeights: "{n} weights",
  inspectTypoStyles: "{n} text styles",
  inspectTypoShowAll: "Show all",
  inspectTypoNone: "No fonts detected on this page.",
  inspectTypoModalTitle: "All fonts",
  inspectClose: "Close",
  inspectColorsTitle: "Colors {n}",
  inspectColorsExportAll: "Export All",
  inspectColorsPalette: "Palette",
  inspectColorsCategories: "Categories",
  inspectColorsNone: "No colors detected on this page.",
  inspectColorLocate: "Locate",
  inspectColorCopy: "Copy",
  inspectColorCopied: "Copied",
  inspectColorLocateCount: "{n} match for {value}",
  inspectColorLocateCountPlural: "{n} matches for {value}",
  inspectColorLocateNone: "No matches for {value}",
  inspectColorLocateError: "Couldn't locate {value}",
  inspectColorCatBackground: "Background colors",
  inspectColorCatText: "Text colors",
  inspectColorCatBorder: "Border colors",
  inspectColorCatFill: "Fill colors",
  inspectColorCatStroke: "Stroke colors",
  inspectColorCatGradient: "Gradients",
  inspectColorCatShadow: "Shadow colors",
  inspectColorCatOther: "Other",
  inspectContrastTitle: "Contrast Scanner",
  inspectContrastShowAll: "Show all",
  inspectContrastFailing: "Failing",
  inspectContrastPassing: "Passing",
  inspectContrastNone: "No text-on-background pairs detected.",
  inspectContrastInstances: "{n} instances",
  inspectContrastShowDetails: "Show details",
  inspectContrastHideDetails: "Hide details",
  inspectContrastText: "Text",
  inspectContrastBackground: "Background",
  inspectContrastNormal: "Normal",
  inspectContrastLarge: "Large",
  inspectContrastBack: "Back",
  inspectCssTitle: "CSS Information",
  inspectCssRules: "CSS rules",
  inspectCssSize: "Inlined CSS",
  inspectCssExternalSheets: "External stylesheets",
  inspectCssInlineTags: "<style> tags",
  inspectCssUnreachable: "Unreachable sheets",
  inspectCssUnreachableHint: "Cross-origin stylesheets without CORS — counts only.",
  inspectCssNone: "No CSS detected on this page.",
  inspectInspectorTitle: "Element Inspector",
  inspectInspectorEmpty: "No elements available to inspect.",
  inspectInspectorHint: "Showing the largest visible elements first. Click any row to view its computed styles.",
  inspectInspectorRect: "{w} × {h}",
  inspectInspectorShowMore: "Show more",
  inspectInspectorShowLess: "Show less",
  inspectInspectorCopySelector: "Copy selector",
  inspectInspectorCopied: "Copied",
  inspectInspectorAnchor: "Set as anchor",
  inspectInspectorAnchored: "Anchor",
  inspectInspectorClearAnchor: "Clear anchor",
  inspectInspectorAnchorBanner: "Anchor: {selector}",
  inspectInspectorDistTitle: "Distance to anchor",
  inspectInspectorDistLeft: "left",
  inspectInspectorDistRight: "right",
  inspectInspectorDistTop: "top",
  inspectInspectorDistBottom: "bottom",
  inspectInspectorDistHGap: "horizontal gap",
  inspectInspectorDistVGap: "vertical gap",
  inspectInspectorDistOverlap: "overlapping",
  inspectInspectorDistSelf: "Anchor selected.",
  inspectInspectorShowCode: "Show code",
  inspectShowCodeTitle: "Show code",
  inspectShowCodeTabHtml: "HTML",
  inspectShowCodeTabCss: "CSS",
  inspectShowCodeCopy: "Copy",
  inspectShowCodeCopied: "Copied",
  inspectShowCodeNote: "Synthesized from the captured snapshot — class names and computed styles only. For full markup use Pick Element export.",
  inspectDetailTitle: "Color details",
  inspectDetailHex: "Hex",
  inspectDetailRgb: "RGB",
  inspectDetailHsl: "HSL",
  inspectDetailAlpha: "Alpha",
  inspectDetailCategory: "Category",
  inspectDetailInstances: "Instances",
  inspectDetailCopyHex: "Copy hex",
  inspectDetailCopyRgb: "Copy rgb()",
  inspectDetailCopyHsl: "Copy hsl()",
  inspectDetailCopied: "Copied",
  inspectExportReport: "Export report",
  inspectExportJson: "JSON",
  inspectExportMarkdown: "Markdown",
  inspectExportColorsCsv: "Colors (CSV)",
  inspectExportFontsCsv: "Fonts (CSV)",
  inspectFooterLabel: "Inspect Page v{version}",
  statusIdle: "Idle",
  statusCollecting: "Collecting page assets…",
  statusCapturing: "Capturing screenshot {done}/{total}",
  statusStitching: "Stitching image…",
  statusBundling: "Building ZIP…",
  statusDownloading: "Downloading…",
  statusPicker: "Picker active. Click (or right-click) an element. Esc to cancel.",
  statusSelecting: "Building element export…",
  statusSuccess: "Saved {filename}",
  statusError: "Error: {message} ({code})",
  settingsHeader: "Settings",
  lblImageFormat: "Image format",
  lblJpegQuality: "JPEG quality",
  lblRedact: "Redact <input type=password> values",
  lblComputed: "Include computed styles",
  lblMatched: "Include matched rules",
  lblNameFull: "Filename — full page",
  lblNameElem: "Filename — element",
  notAvailable: "Not available on browser pages.",
  telemetryHeader: "Captured in this export",
  telemetryShadowRoots: "shadow roots",
  telemetryFonts: "fonts",
  telemetryIframesSame: "same-origin iframes",
  telemetryIframesCross: "cross-origin iframes (skipped)",
  telemetryStylesheets: "stylesheets",
  telemetryFrames: "screenshot tiles",
  telemetryElementOuterHtml: "outerHTML",
  telemetryElementMatchedRules: "matched CSS rules",
  telemetryElementComputedDiff: "computed-style diffs",
  telemetryElementScreenshots: "screenshots (context + isolated)",
  telemetryElementIsolatedSkipped: "isolated skipped",
  debugHeader: "Picked element",
  debugSelector: "Selector",
  debugTabHtml: "HTML",
  debugTabCss: "CSS",
  debugTabJs: "JS",
  debugCopy: "Copy",
  debugFormatLabel: "Format",
  debugFormatRaw: "Raw",
  debugFormatMd: "Markdown",
  debugDownloadCurrent: "Download current",
  debugDownloadAll: "Download all (zip)",
  debugClear: "Clear",
  debugJsEmpty: "Element-scoped JS is not extracted. Showing computed-style diff (JSON).",
  fullPageActionsHeader: "Re-download captured files",
  fullPageDownloadHtml: "HTML",
  fullPageDownloadCss: "CSS",
  fullPageDownloadJs: "JS",
  fullPageDownloadScreenshot: "Screenshot",
  fullPageDownloadAllZip: "Download all (zip)",
  exportModesHeader: "Export for AI",
  exportModeMd: "MD",
  exportModeMdFiles: "MD + files",
  exportModeZip: "ZIP",
  exportModeShare: "Share Links",
  exportModeShareDisabledTip: "Sign in to Inspect Page in Settings → Smart Share",
  onboardingTitle: "Smart Share",
  onboardingBody: "Sign in to your WordPress account to create shareable links that expire in 24 hours.",
  onboardingDismiss: "Got it",
  onboardingSignIn: "Sign in",
  shareSettingsHeader: "Smart Share",
  shareHelp: "Sign in once with the Inspect Page account — no passwords or tokens are saved on your device.",
  shareNotConfiguredMsg: "Smart Share is being set up. This export mode will be available shortly.",
  shareSignInBtn: "Sign in",
  shareSignOutBtn: "Sign out",
  shareCheckBtn: "I'm signed in — refresh",
  shareSignedInAsPrefix: "Signed in as",
  shareSignedOutMsg: "Not signed in to this site.",
  shareBadUrlMsg: "Enter a valid http(s) site URL (e.g. https://example.com).",
  shareLoginOpenedMsg: "A WordPress login tab was opened. Sign in there, then come back and click \"refresh\".",
  shareUploading: "Uploading to WordPress…",
  shareCopied: "4 URLs + AI prompt copied to clipboard",
  shareExpiresInPrefix: "Expires in",
  shareDialogHeader: "Share links created",
  shareDialogIntro: "These 4 URLs are publicly fetchable for 24 hours. Anyone with a link can read the file.",
  shareLblHtml: "HTML",
  shareLblCss: "CSS",
  shareLblJs: "JS",
  shareLblImage: "Image",
  shareCopyOne: "Copy",
  shareCopyAll: "Copy AI prompt + 4 URLs",
  shareCopyAllDone: "Copied!",
  shareCopyOneDone: "Copied",
  shareRevokeBtn: "Revoke now",
  shareRevokedMsg: "Revoked. The links no longer work.",
  shareRevokingMsg: "Revoking…",
  shareCloseBtn: "Close",
  shareExpiredMsg: "Expired",
  shareQuotaPrefix: "Free shares used:",
  shareQuotaUnlimited: "Pro plan — unlimited shares",
  shareUpgradeHint: "Upgrade to Pro for unlimited shares",
  shareUpgradeBtn: "Upgrade to Pro",
  shareManageSubscriptionBtn: "Manage subscription",
  /** Phase 3 — plan badge / pricing card in Settings popover. */
  billingPlanLabel: "Plan",
  billingPlanFree: "Free",
  billingPlanPro: "Pro",
  billingSubscriptionLabel: "Subscription",
  billingPriceTagline: "$5 / month — unlimited Smart Shares",
  billingUpgradeAlwaysHint: "Tip: Pro removes the 5-share lifetime cap.",
  shareQuotaFreeReachedMsg: "Free quota reached. Upgrade to Inspect Page Pro to keep sharing.",
  /** 2.6.0 — Pricing card bullets shown on Free plan. */
  billingFeatureUnlimited: "Unlimited Smart Shares (no 5-share cap)",
  billingFeaturePriority: "Priority share-link delivery",
  billingFeatureVisitors: "Recent visitors drawer in WP admin",
  billingFeatureSupport: "Email support from the maintainer",
  /** 2.6.0 — success toast after Stripe Checkout flips license to Pro. */
  billingProToast: "You're Pro 🎉 — unlimited Smart Shares unlocked.",
  /** 2.7.0 — Team Workspaces UI surfaces. */
  workspaceLabel: "Workspace",
  workspaceRoleOwner: "Owner",
  workspaceRoleAdmin: "Admin",
  workspaceRoleMember: "Member",
  workspaceLicenseFree: "Free",
  workspaceLicenseActive: "Pro",
  workspaceLicensePastDue: "Past due",
  workspaceLicenseCanceled: "Canceled",
  workspaceLoadingMsg: "Loading workspaces…",
  workspaceNoneMsg: "No workspace selected.",
  workspaceRecentLabel: "Showing recent shares for",
} as const;

export type CopyKey = keyof typeof COPY;

/**
 * Canonical AI instruction block embedded in every export mode.
 * Source: spec/21-app/24-export-modes.md §D.
 * Tokens: {{HTML_REF}}, {{CSS_REF}}, {{JS_REF}}, {{IMAGE_REF}}.
 */
export const AI_INSTRUCTION_BLOCK = `I'm sharing a UI component with you. Please read all four files first, then apply the change I describe at the end.

HTML:    {{HTML_REF}}
CSS:     {{CSS_REF}}
JS:      {{JS_REF}}
Image:   {{IMAGE_REF}}

Instructions:
1. Fetch and read the HTML to understand the current markup and structure.
2. Fetch and read the CSS to understand the current styling, tokens, and breakpoints.
3. Fetch and read the JS to understand any current behavior.
4. Open the image to see how the component currently renders.
5. Then make the change requested below — modify HTML/CSS/JS only. Do not break the existing structure, semantics, or responsiveness unless I ask for it. You may add animations, restyle, or adjust layout.

My request:
<write your change request here>
`;

export interface AiRefs {
  htmlRef: string;
  cssRef: string;
  jsRef: string;
  imageRef: string;
}

/** Replace {{HTML_REF}} / {{CSS_REF}} / {{JS_REF}} / {{IMAGE_REF}} placeholders. */
export function interpolateAi(refs: AiRefs): string {
  return AI_INSTRUCTION_BLOCK
    .replace("{{HTML_REF}}", refs.htmlRef)
    .replace("{{CSS_REF}}", refs.cssRef)
    .replace("{{JS_REF}}", refs.jsRef)
    .replace("{{IMAGE_REF}}", refs.imageRef);
}
