// Code generated by linters-cicd/codegen/inverted_fields.py — DO NOT EDIT.
// Source: Rule 9, spec/04-database-conventions/01-naming-conventions.md
//
// Each method below is a computed inverse of a stored boolean column.
// The database stores ONLY the canonical (positive) form; the inverse
// is derived in code with a single negation. Never persist these.

package models


// --- User: derived inverses ---

// IsInactive is derived from IsActive (db column: IsActive).
func (m User) IsInactive() bool { return !m.IsActive }

// HasNoLicense is derived from HasLicense (db column: HasLicense).
func (m User) HasNoLicense() bool { return !m.HasLicense }

// --- Subscription: derived inverses ---

// IsDisabled is derived from IsEnabled (db column: IsEnabled).
func (m Subscription) IsDisabled() bool { return !m.IsEnabled }

// IsUnverified is derived from IsVerified (db column: IsVerified).
func (m Subscription) IsUnverified() bool { return !m.IsVerified }
