// Code generated by linters-cicd/codegen/inverted_fields.py — DO NOT EDIT.
// Source: Rule 9, spec/04-database-conventions/01-naming-conventions.md
//
// Each getter below is a computed inverse of a stored boolean column.
// The database stores ONLY the canonical (positive) form; the inverse
// is derived in code with a single negation. Never persist these.


export abstract class UserInvertedFields {
  readonly IsActive!: boolean;
  readonly HasLicense!: boolean;

  /** Derived from IsActive (db column: IsActive). */
  get IsInactive(): boolean {
    return !this.IsActive;
  }

  /** Derived from HasLicense (db column: HasLicense). */
  get HasNoLicense(): boolean {
    return !this.HasLicense;
  }
}

export abstract class SubscriptionInvertedFields {
  readonly IsEnabled!: boolean;
  readonly IsVerified!: boolean;

  /** Derived from IsEnabled (db column: IsEnabled). */
  get IsDisabled(): boolean {
    return !this.IsEnabled;
  }

  /** Derived from IsVerified (db column: IsVerified). */
  get IsUnverified(): boolean {
    return !this.IsVerified;
  }
}
