<?php
/**
 * Code generated by linters-cicd/codegen/inverted_fields.py — DO NOT EDIT.
 * Source: Rule 9, spec/04-database-conventions/01-naming-conventions.md
 *
 * Each method below is a computed inverse of a stored boolean column.
 * The database stores ONLY the canonical (positive) form; the inverse
 * is derived in code with a single negation. Never persist these.
 */


trait UserInvertedFields
{
    /** Derived from \$IsActive (db column: IsActive). */
    public function getIsInactive(): bool
    {
        return !$this->IsActive;
    }

    /** Derived from \$HasLicense (db column: HasLicense). */
    public function getHasNoLicense(): bool
    {
        return !$this->HasLicense;
    }

}

trait SubscriptionInvertedFields
{
    /** Derived from \$IsEnabled (db column: IsEnabled). */
    public function getIsDisabled(): bool
    {
        return !$this->IsEnabled;
    }

    /** Derived from \$IsVerified (db column: IsVerified). */
    public function getIsUnverified(): bool
    {
        return !$this->IsVerified;
    }

}
